apiVersion: v1
kind: Secret
metadata:
  name: backtrace-secrets
  namespace: backtrace-prod
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCs0eHBlYzovL3Bvc3RncmVzOmJhY2t0cmFjZV9wcm9kX3Bhc3NAcG9zdGdyZXM6NTQzMi9iYWNrdHJhY2VfcHJvZA== # base64 encoded string
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfcHJvZF9iYWNrdHJhY2U=
